/*
 *   ----------------------
 *  |  ActorNativeClass.h
 *   ----------------------
 *   This file is part of ImageLoader for UT99.
 *
 *   ChatDiamond is free software: you can redistribute and/or modify
 *   it under the terms of the Open Unreal Mod License version 1.1.
 *
 *   ImageLoader is distributed in the hope and belief that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *   You should have received a copy of the Open Unreal Mod License
 *   along with ImageLoader.  If not, see
 *   <https://beyondunrealwiki.github.io/pages/openunrealmodlicense.html>.
 *
 *   Timeline:
 *   May, 2023 - Concept and implementation
 */

 /*======================================================================================================
	 C++ class definitions exported from UnrealScript.
	 This is automatically generated by the tools.
	 DO NOT modify this manually! Edit the corresponding .uc files instead!
	 Ok you can modify it manually, but be smart about it. Backups.

	 No clue how you exported .uc to .h. Lemme leverage the smartness anyway!
	 https://www.oldunreal.com/phpBB3/viewtopic.php?f=37&t=3938
 ========================================================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,4)
#endif


 #ifndef NAMES_ONLY
 #define AUTOGENERATE_FUNCTION(cls,idx,name)
 #endif

//#ifndef NAMES_ONLY

class AImageLoader : public AActor
{
public:
	DECLARE_FUNCTION(execTestFunction)
	DECLARE_FUNCTION(execGetGameSystemPath)
	DECLARE_FUNCTION(execDeSerializeJson)
	DECLARE_CLASS(AImageLoader, AActor, 0, ImageLoader);
	AImageLoader();
};

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ACDDiscordActor)
#endif // VERIFY_CLASS_SIZES

/*
 *
 *		                                  /\
 *		                                 / /
 *		                              /\| |
 *		                              | | |/\
 *		                              | | / /
 *		                              | `  /
 *		                              `\  (___
 *		                             _.->  ,-.-.
 *		                          _.'      |  \ \
 *		                         /    _____| 0 |0\
 *		                        |    /`    `^-.\.-'`-._
 *		                        |   |                  `-._
 *		                        |   :                      `.
 *		                        \    `._     `-.__         O.'
 *		 _.--,                   \     `._     __.^--._O_..-'
 *		`---, `.                  `\     /` ` `
 *		     `\ `,                  `\   |
 *		      |   :                   ;  |
 *		      /    `.              ___|__|___
 *		     /       `.           (          )
 *		    /    `---.:____...---' `--------`.
 *		   /        (         `.      __      `.
 *		  |          `---------' _   /  \       \
 *		  |    .-.      _._     (_)  `--'        \
 *		  |   (   )    /   \                       \
 *		   \   `-'     \   /                       ;-._
 *		    \           `-'           \           .'   `.
 *		    /`.                  `\    `\     _.-'`-.    `.___
 *		   |   `-._                `\    `\.-'       `-.   ,--`
 *		    \      `--.___        ___`\    \           ||^\\
 *		     `._        | ``----''     `.   `\         `'  `
 *		        `--;     \  jgs          `.   `.
 *		           //^||^\\               //^||^\\
 *		           '  `'  `               '   '  `
 */